#!/usr/bin/env python3
from pathlib import Path
from urllib.request import urlretrieve

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "tools" / "fonts" / "literata"
OUT = ROOT / "display" / "src" / "literata_generated.rs"

BASE = "https://raw.githubusercontent.com/googlefonts/literata/main/fonts/ttf"
FONTS = [
    ("REGULAR", "Literata-Regular.ttf"),
    ("ITALIC", "Literata-Italic.ttf"),
    ("BOLD", "Literata-Bold.ttf"),
    ("BOLD_ITALIC", "Literata-BoldItalic.ttf"),
]

FIRST = 0x20
LAST = 0xFF
PX = 22
LINE_HEIGHT = 30
BASELINE = 23


def ensure_fonts():
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    for _, name in FONTS:
        path = FONT_DIR / name
        if not path.exists():
            urlretrieve(f"{BASE}/{name}", path)


def glyph(font, code):
    ch = chr(code)
    bbox = font.getbbox(ch, anchor="ls")
    advance = int(round(font.getlength(ch)))
    if bbox is None:
        return (0, 0, 0, 0, max(advance, 1), [])
    left, top, right, bottom = bbox
    width = max(0, right - left)
    height = max(0, bottom - top)
    if width == 0 or height == 0:
        return (0, 0, left, top, max(advance, 1), [])
    image = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(image)
    draw.text((-left, -top), ch, font=font, fill=255, anchor="ls")
    rows = []
    for y in range(height):
        byte = 0
        bits = 0
        for x in range(width):
            if image.getpixel((x, y)) >= 128:
                byte |= 0x80 >> bits
            bits += 1
            if bits == 8:
                rows.append(byte)
                byte = 0
                bits = 0
        if bits:
            rows.append(byte)
    return (width, height, left, top, max(advance, 1), rows)


def main():
    ensure_fonts()
    out = []
    out.append("// Generated by tools/generate_literata.py. Do not edit by hand.\n")
    out.append("use crate::font::{BitmapFont, GlyphMetric};\n\n")
    out.append(f"pub const LITERATA_FIRST: u16 = {FIRST};\n")
    out.append(f"pub const LITERATA_LAST: u16 = {LAST};\n")
    out.append(f"pub const LITERATA_COUNT: usize = {LAST - FIRST + 1};\n\n")

    font_consts = []
    for style, filename in FONTS:
        font = ImageFont.truetype(str(FONT_DIR / filename), PX)
        metrics = []
        bitmap = []
        offset = 0
        for code in range(FIRST, LAST + 1):
            width, height, x_offset, y_offset, advance, rows = glyph(font, code)
            metrics.append((offset, len(rows), width, height, x_offset, y_offset, advance))
            bitmap.extend(rows)
            offset += len(rows)

        out.append(f"pub static LITERATA_{style}_METRICS: [GlyphMetric; LITERATA_COUNT] = [\n")
        for item in metrics:
            out.append(
                "    GlyphMetric { "
                f"offset: {item[0]}, len: {item[1]}, width: {item[2]}, height: {item[3]}, "
                f"x_offset: {item[4]}, y_offset: {item[5]}, advance: {item[6]} }},\n"
            )
        out.append("];\n\n")

        out.append(f"pub static LITERATA_{style}_BITMAP: [u8; {len(bitmap)}] = [\n")
        for chunk_start in range(0, len(bitmap), 16):
            chunk = bitmap[chunk_start : chunk_start + 16]
            out.append("    ")
            out.append(", ".join(f"0x{b:02X}" for b in chunk))
            out.append(",\n")
        out.append("];\n\n")

        const_name = f"LITERATA_{style}"
        font_consts.append(const_name)
        out.append(f"pub static {const_name}: BitmapFont = BitmapFont {{\n")
        out.append("    first: LITERATA_FIRST,\n")
        out.append("    last: LITERATA_LAST,\n")
        out.append(f"    line_height: {LINE_HEIGHT},\n")
        out.append(f"    baseline: {BASELINE},\n")
        out.append(f"    metrics: &LITERATA_{style}_METRICS,\n")
        out.append(f"    bitmap: &LITERATA_{style}_BITMAP,\n")
        out.append("};\n\n")

    OUT.write_text("".join(out))


if __name__ == "__main__":
    main()
